<b>Consigna</b>: Replicar el siguiente laboratorio practico donde se desarrolla un ejemplo
complementario del uso de NLTK para el análisis de texto. El alumno, deberá ejecutar el script
en un notebook y compartirlo para su corrección. A su vez, se le solicita al estudiante explicar lo
que se esta realizando paso a paso como así también, incluir una conclusión que resuma los
principales aprendizajes de la actividad junto con la integración de los conceptos vistos y
estudiados a lo largo del Sprint.

## Primer Paso

Se importan las librerías necesarias para el procesamiento del texto y gestión de datos. Importamos json y re para trabajar con archivos JSON y re para trabajar con expresiones regulares. Después importamos pandas para poder procesar los datos utilizando DataFrames. La importación de las diferentes funciones de nltk se emplearán en el propio procesamiento de texto.

In [ ]:
# Importación de librerías necesarias
import json, re
import pandas as pd
from nltk.corpus import stopwords
from nltk.stem import SnowballStemmer
from nltk.tokenize import ToktokTokenizer

## Segundo paso

A continuación se abre el archivo de texto, empleando el formato json y se leen los datos del fichero. A partir de estos datos, se busca en el JSON el titular de la noticia y el cuerpo de la misma, guardándose cada una como una lista de tuplas. Posteriormente, estos datos se transforman en un dataframe con pandas.

In [ ]:
# Abrimos el archivo noticias en formato JSON 
with open('noticias.txt') as json_file:
    datos = json.load(json_file)
    
# Parseamos los datos, cargando el titular y el cuerpo de la noticia
tuplas = list(zip([noticia.get("titular") for noticia in datos],
                [noticia.get("texto") for noticia in datos]))

# Almacenamos los datos en un DataFrame de pandas
df = pd.DataFrame(tuplas, columns =['Titular', 'Noticia'])
print(df.shape)

df.head()

(5665, 2)

,Titular,Noticia
0,Un estudio impulsado por la Universidad de San...,El virus SARS-Cov-2 entró en España por la ciu...
1,Las claves: qué es Montai y quién está detrás,¿Qué es Montai? ¿Qué relación guarda con las o...
2,Robots entregan domicilios en Medellín durante...,Unos 15 robots recorren las calles de Medellín...
3,Grazón insiste en que un nuevo estado de alarm...,"En una entrevista en Radio Euskadi, recogida p..."
4,Vox se sube a la ola de la extrema derecha eur...,"""España ha dejado de ser católica"", decía Manu..."

## Tercer paso

En las siguientes celdas de código, vamos a definir una función para realizar una limpieza del texto, empleando para ello funciones regulares. Esta funcción va a servir para eliminar caracteres que no nos aportan información, en este caso, aquellos no alfanuméricos que aparezcan en el texto, así como conectores de una única letra y espacios múltiples consecutivos. Por último, se convierte todo el texto en minúsculas y se devuelve el resultado.

Seguidamente, se emplea esta función sobre el dataframe para generar una nueva columna con el texto limpio, que denominaremos "Tokens".

In [ ]:
# Definimos una función para limpiar el texto
def limpiar_texto(texto):
    
    texto = re.sub(r'\W', ' ', str(texto))
    texto = re.sub(r'\s+[a-zA-Z]\s+', ' ', texto)
    texto = re.sub(r'\s+', ' ', texto, flags=re.I)
    texto = texto.lower()
    
    return texto

In [ ]:
#Creamos la columna tokens con los datos limpios
df["Tokens"] = df.Noticia.apply(limpiar_texto)
df.head()

,Titular,Noticia,Tokens
0,Un estudio impulsado por la Universidad de San...,El virus SARS-Cov-2 entró en España por la ciu...,el virus sars cov 2 entró en españa por la ciu...
1,Las claves: qué es Montai y quién está detrás,¿Qué es Montai? ¿Qué relación guarda con las o...,qué es montai qué relación guarda con las otr...
2,Robots entregan domicilios en Medellín durante...,Unos 15 robots recorren las calles de Medellín...,unos 15 robots recorren las calles de medellín...
3,Grazón insiste en que un nuevo estado de alarm...,"En una entrevista en Radio Euskadi, recogida p...",en una entrevista en radio euskadi recogida po...
4,Vox se sube a la ola de la extrema derecha eur...,"""España ha dejado de ser católica"", decía Manu...",españa ha dejado de ser católica decía manuel...

## Cuarto Paso

En la siguiente celda de código vamos a definir la función necesaria para convertir el texto en tokens, que ha sido previamente importada de la librería nltk. Aplicaremos este método de tokenización a la columna "Tokens" de nuestro DataFrame, que contiene el texto del cuerpo de las noticias limpiado previamente.

In [8]:
#Completar con la explicacion
tokenizer = ToktokTokenizer()
df["Tokens"] = df.Tokens.apply(tokenizer.tokenize)
df.head()

,Titular,Noticia,Tokens
0,Un estudio impulsado por la Universidad de San...,El virus SARS-Cov-2 entró en España por la ciu...,"[el, virus, sars, cov, 2, entró, en, españa, p..."
1,Las claves: qué es Montai y quién está detrás,¿Qué es Montai? ¿Qué relación guarda con las o...,"[qué, es, montai, qué, relación, guarda, con, ..."
2,Robots entregan domicilios en Medellín durante...,Unos 15 robots recorren las calles de Medellín...,"[unos, 15, robots, recorren, las, calles, de, ..."
3,Grazón insiste en que un nuevo estado de alarm...,"En una entrevista en Radio Euskadi, recogida p...","[en, una, entrevista, en, radio, euskadi, reco..."
4,Vox se sube a la ola de la extrema derecha eur...,"""España ha dejado de ser católica"", decía Manu...","[españa, ha, dejado, de, ser, católica, decía,..."

## Quinto paso

En esta fase vamos a emplear las stopwords en castellano que están disponibles en la biblioteca NLTK. Estas son palabras como conectores, adverbios y preposiciones que no aportan mucha información para el procesamiento del texto. Para usar esta librería vamos a tener que descargar el paquete y establecer el conjunto de palabras para el idioma seleccionado. Después definimos una función que recorre las listas de tokens de cada noticia y los elimina si aparecen en la lista de stopwords, y aplicamos dicha función a la columna "Tokens" del DataFrame.

In [10]:
# Añadido para utilizar stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Usuario\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [11]:
#Completar con la explicacion
STOPWORDS = set(stopwords.words("spanish"))

def filtrar_stopword_digitos(tokens):
    return [token for token in tokens if token not in STOPWORDS and not token.isdigit()]

df["Tokens"] = df.Tokens.apply(filtrar_stopword_digitos)
df.head()

,Titular,Noticia,Tokens
0,Un estudio impulsado por la Universidad de San...,El virus SARS-Cov-2 entró en España por la ciu...,"[virus, sars, cov, entró, españa, ciudad, vito..."
1,Las claves: qué es Montai y quién está detrás,¿Qué es Montai? ¿Qué relación guarda con las o...,"[montai, relación, guarda, empresas, quién, de..."
2,Robots entregan domicilios en Medellín durante...,Unos 15 robots recorren las calles de Medellín...,"[robots, recorren, calles, medellín, realizar,..."
3,Grazón insiste en que un nuevo estado de alarm...,"En una entrevista en Radio Euskadi, recogida p...","[entrevista, radio, euskadi, recogida, europa,..."
4,Vox se sube a la ola de la extrema derecha eur...,"""España ha dejado de ser católica"", decía Manu...","[españa, dejado, ser, católica, decía, manuel,..."

## Sexto paso

A continuación vamos a proceder con el stemming de las palabras. Este proceso supone una reducción de cada palabra a su raíz semántica, también denominado lexema. Para ello vamos a el método SnowballStemmer de la librería NLTK, ajustado para el idioma castellano. Creamos una función que recorra una lista de tokens y extraiga su lexema, y aplicamos dicha función a columna con las listas de tokens de cada noticia. Por último, mostramos los primeros 10 resultados de la primera noticia, para ver el efecto del stemming.

In [12]:
#Completar con la explicación
stemmer = SnowballStemmer("spanish")
def stem_palabras(tokens):
    """
    Reduce cada palabra de una lista dada a su raíz.
    """
    return [stemmer.stem(token) for token in tokens]

df["Tokens"] = df.Tokens.apply(stem_palabras)
df.head()

,Titular,Noticia,Tokens
0,Un estudio impulsado por la Universidad de San...,El virus SARS-Cov-2 entró en España por la ciu...,"[virus, sars, cov, entro, españ, ciud, vitori,..."
1,Las claves: qué es Montai y quién está detrás,¿Qué es Montai? ¿Qué relación guarda con las o...,"[montai, relacion, guard, empres, quien, detra..."
2,Robots entregan domicilios en Medellín durante...,Unos 15 robots recorren las calles de Medellín...,"[robots, recorr, call, medellin, realiz, entre..."
3,Grazón insiste en que un nuevo estado de alarm...,"En una entrevista en Radio Euskadi, recogida p...","[entrev, radi, euskadi, recog, europ, press, g..."
4,Vox se sube a la ola de la extrema derecha eur...,"""España ha dejado de ser católica"", decía Manu...","[españ, dej, ser, catol, dec, manuel, azañ, co..."

In [13]:
#Completar con la explicación
print(df.Tokens[0][0:10])

['virus', 'sars', 'cov', 'entro', 'españ', 'ciud', 'vitori', 'torn', 'febrer', 'conclusion']

## CONCLUSIÓN

El presente notebook ha demostrado de manera práctica y sistemática cómo implementar una pipeline completa de preprocesamiento de texto para análisis de lenguaje natural, empleando para ello librería NLTK en Python. A través de los seis pasos ejecutados, hemos leído y almacenado exitosamente un conjunto de noticias contenidas en un archivo JSON, y hemos transformado el cuerpo de las mismas en listas de tokens procesados y normalizados, listos para análisis posteriores.

### Proceso de Transformación Integral:

El proceso comenzó con la carga estructurada de datos desde un archivo JSON, almacenando los datos en tuplas de título y cuerpo de noticia. La utilización de pandas para crear un DataFrame a partir de los datos previos facilitó significativamente el manejo y procesamiento posterior de la información, estableciendo las bases sólidas para un análisis sistemático y eficiente. Esta fase inicial destacó la importancia de la estructuración adecuada de datos como prerequisito fundamental para cualquier proyecto de NLP.

La limpieza del texto constituyó un punto muy importante del proceso. Mediante el uso estratégico de expresiones regulares, se eliminaron caracteres no alfanuméricos, conectores de una sola letra y espacios múltiples generados en los pasos anteriores, además de normalizar todo el contenido a minúsculas. Esta etapa resultó crucial para estandarizar el formato del texto y eliminar ruido que podría interferir significativamente en análisis posteriores, dado que podrían reconocerse palabras idénticas como diferentes o incorporar gran cantidad de datos que no aportan información, demostrando cómo pequeños ajustes en la preparación de datos pueden impactar dramáticamente la calidad de los resultados finales.

### Tokenización y Filtrado Estratégico:

La tokenización transformó el texto limpio en listas de palabras individuales utilizando ToktokTokenizer de NLTK, proceso esencial para dividir el texto continuo en unidades procesables que permiten el análisis palabra por palabra. La implementación efectiva de esta tokenización demostró ser fundamental para cualquier tarea de NLP posterior, estableciendo la granularidad apropiada para el análisis textual.

El filtrado de stopwords sibre para filtrar palabras comunes del castellano, tales como como artículos, preposiciones y conectores que no aportan valor semántico significativo al análisis de las noticias. Adicionalmente, eliminamos los dígitos numéricos, lo que permite reducir la dimensionalidad del vocabulario, enfocándose únicamente en palabras con carga semántica. Esta etapa demuestra cómo la reducción inteligente de datos puede mejorar tanto la eficiencia computacional como la precisión de análisis posteriores.

### Stemming y Normalización Morfológica:

El stemming es un proceso que reduce los tokens a su raiz semántica, o lexema, que es compartido por todas las palabras de una misma familia, de modo que "perro", "perrera" y "perrito" serían todas almacenadas como "perr". Este proceso resultó fundamental para reducir la variabilidad léxica y mejorar la identificación de patrones en el texto, demostrando cómo la normalización morfológica puede revelar conexiones semánticas que de otro modo no podrían ser identificadas por la máquina.

### Integración de Conceptos y Aprendizajes Clave:

Este notebook, por tanto, ha integrado exitosamente conceptos fundamentales del procesamiento de lenguaje natural vistos durante el presente Sprint, demostrando cómo transformar texto libre en representaciones procesables por algoritmos de machine learning. La secuencia metodológica seguida representa una pipeline estándar en NLP, véase: carga de datos → limpieza → tokenización → filtrado → normalización, estableciendo un marco de trabajo replicable para proyectos similares.

La actividad permitió aplicar conocimientos sobre expresiones regulares, estructuras de datos de Python, y técnicas específicas de NLP. Además, la combinación efectiva de herramientas como pandas para manejo de datos y NLTK para procesamiento de texto ilustró la naturaleza interdisciplinaria del análisis de texto moderno, donde la integración de múltiples tecnologías es esencial para obtener resultados óptimos.

### Aplicabilidad práctica futura:

Los tokens procesados están ahora preparados para tareas avanzadas como análisis de sentimientos, clasificación automática de texto, modelado de temas, sistemas de recomendación o análisis de tendencias. La calidad del preprocesamiento realizado determinará directamente la efectividad de estos análisis posteriores, subrayando la importancia crítica de esta fase inicial.

En conclusión, el trabajo desarrollado en este Sprint ha establecido bases sólidas para el análisis de texto automatizado, demostrando que un preprocesamiento riguroso y sistemático es esencial para obtener resultados significativos y confiables en proyectos de procesamiento de lenguaje natural. La metodología aplicada constituye un framework reproducible y escalable para futuros proyectos de análisis textual.