<h1 style="text-align:center">Sistemas de recomendacion: Sprint 2</h1>
<p style="text-align:center"><em>Autor: Adrián Robles Arques</em></p>

En este trabajo vamos a revisar dos casos y analizar los posibles resultados a los problemas planteados, justificando la respuesta correcta, así como señalando los errores de las incorrectas.

# CASO 1: Distancia euclidea entre inmuebles

Para este caso contamos con datos de ubicaciones relativas a una serie de inmuebles ubicados en una ciudad, considerando las coordenadas definidas en el plano con un sistema de referencia propio. Asumiendo una geometría plana, definimos el espacio vectorial donde se ubican los vectores que determinan la posición de cada uno de los inmuebles, y podemos dotarlo de la métrica euclidea usual para un espacio de dos dimensiones, que se define como:

$$
ds^2 = dx^2 + dy^2
$$

Se nos plantean tres posibles soluciones empleando código de python para calcular esta distancia, entre las cuales la única correcta es la opción A, puesto que en primer lugar calcula el vector diferencia entre los vectores de posición de dos inmebles a y b, y después aplica el cálculo de la métrica sobre el vector resultante. Mostraremos un ejemplo a continuación:

In [1]:
# Importamos librerias
from math import sqrt
import numpy as np

In [2]:
# Datos del ejemplo
departamento1132 = np.array([1,4])
departamento2859 = np.array([3,4.5])
casa5687 = np.array([3,4.5])
casa6295 = np.array([5,2.5])

In [14]:
# Introducimos la función que consideramos correcta, la opción A
def pitagoras(a,b):
    (delta_x, delta_y) = a - b
    return sqrt(delta_x*delta_x + delta_y*delta_y)

# Como vemos esta función actua tal como se espera
print(f'distancia entre departamento 1132 y casa 5687: {pitagoras(departamento1132, casa5687)}')

distancia entre departamento 1132 y casa 5687: 2.0615528128088303

In [15]:
# Comparamos con el módulo de los vectores posición
mod_departamento1132 = np.linalg.norm(departamento1132)
mod_casa5687 = np.linalg.norm(casa5687)
print(f'modulo del vector posición del departamento 1132 es {mod_departamento1132}')
print(f'modulo del vector posición de la casa 5687 es {mod_casa5687}')

modulo del vector posición del departamento 1132 es 4.123105625617661
modulo del vector posición de la casa 5687 es 5.408326913195984

Esta función es correcta, dado que el módulo del vector a-b debe cumplir con la desigualdad triangular, es decir, que a-b (la distancia entre los inmuebes) sea menor o igual al módulo de cada vector a y b.
La función es correcta y cumple con la desigualdad triangular.

In [10]:
# A continuación definimos las otras dos funciones, que resultan ser incorrectas
def pitagoras_b(a,b):
    (delta_x, delta_y) = a + b
    return sqrt(delta_x*delta_x + delta_y*delta_y)

In [16]:
# Comprobemos cómo esta función no cumple la desigualdad triangular
print(f'distancia entre departamento1132 y casa5687: {pitagoras_b(departamento1132, casa5687)}')
print(f'modulo del vector posición del departamento 1132 es {mod_departamento1132}')
print(f'modulo del vector posición de la casa 5687 es {mod_casa5687}')

distancia entre departamento1132 y casa5687: 9.394147114027968
modulo del vector posición del departamento 1132 es 4.123105625617661
modulo del vector posición de la casa 5687 es 5.408326913195984

Vemos que esta función no puede estar calculando adecuadamente el módulo del vector distancia, dado que incumple la desigualdad triangular.

In [17]:
# Por último, la función c no es operativa, dado que no admite ningún vector de entrada
def pitagoras_c():
    (delta_x, delta_y) = a - b
    return sqrt(delta_x * delta_x + delta_y * delta_y)

In [19]:
# Intentamos calcular el módulo de la resta de dos vectores
pitagoras_c()

NameError: name 'a' is not defined

In [20]:
# Vemos que nos da error, porque los vectores no están definidos
# Pero si le pasamos dos vectores, dará error porque no está diseñada para admitir ninguna variable de entrada
pitagoras_c(departamento1132, casa5687)

TypeError: pitagoras_c() takes 0 positional arguments but 2 were given

Con esto vemos que la función de la opción c no es operativa, puesto que da error en cualquier caso.

# CASO 2: Comparativo de ventas entre regiones

En este caso exploramos cómo realizar adecuadamente un filtrado de datos con pandas, empleando para ello información de dos datasets diferentes, y teniendo la necesidad de cruzar datos para verificar que un mismo identificador aparece en ambos datasets. Para ello, emplearemos el método join presente en los Dataframes de pandas.

Se nos plantean tres posibles soluciones para cruzar datos, donde la solución más adecuada considero que es la A, dado que especifica los sufijos adecuados para cada conjunto de datos en la unión, y además tras unir los dataframes usando el citado método, elimina aquellas filas donde solo aparece uno de los datos y el otro queda vacío, ejecutando de esta forma una unión interior de los conjuntos.

In [25]:
# Generamos el código de prueba para las ventas del norte y del sur a partir de lo mostrado en la documentación

# Importamos las librerías necesarias
import pandas as pd

# Generamos los dos dataframes
ventas_region_norte = pd.DataFrame({'id_producto': [100, 200, 225, 280, 353], 'qtd_ventas': [231, 965,  256, 417, 48]}).set_index('id_producto')

ventas_region_sur = pd.DataFrame({'id_producto': [100, 212, 260, 280, 353], 'qtd_ventas': [187, 565, 156, 754, 98]}).set_index('id_producto')

In [26]:
ventas_region_norte.head()

             qtd_ventas
id_producto
100                 231
200                 965
225                 256
280                 417
353                  48

In [27]:
ventas_region_sur.head()

             qtd_ventas
id_producto
100                 187
212                 565
260                 156
280                 754
353                  98

In [28]:
# Veamos el resultado de la solución A
ventas_regiones = ventas_region_norte.join(ventas_region_sur, lsuffix= '_norte', rsuffix= '_sur').dropna()
ventas_regiones.head()

             qtd_ventas_norte  qtd_ventas_sur
id_producto
100                       231           187.0
280                       417           754.0
353                        48            98.0

Vemos que con esta solución está cruzando los datos que aparecen en la región norte y la sur con el mismo Id de producto, y mostrándolos en columnas separadas, donde el resultado se puede comprar, por lo que esta sería la mejor de las tres.

In [30]:
# Comprobemos el resultado de la solución B
ventas_regiones_b = ventas_region_norte.join(ventas_region_sur).dropna()
ventas_regiones_b.head()

ValueError: columns overlap but no suffix specified: Index(['qtd_ventas'], dtype='object')

La opción B va a dar error tal como está expresada, pueso que al no aplicar un sufijo las dos columnas se solapan pues comparten nombre, que es el identificador de columna que utiliza pandas.

In [31]:
ventas_regiones_c = ventas_region_norte.join(ventas_region_sur, lsuffix= '_norte', rsuffix= '_sur')
ventas_regiones_c.head()

             qtd_ventas_norte  qtd_ventas_sur
id_producto
100                       231           187.0
200                       965             NaN
225                       256             NaN
280                       417           754.0
353                        48            98.0

Esta solución, aunque funcional, realiza una unión exterior hacia la izquierda, mostrando todos los datos de ventas en la región norte y aquellos de la B que coinciden en Id de producto, pero dejando huecos en los que sí aparecen en la A pero no en la B.

Esta misma lógica de programación podría aplicarse alternativamente empleando la función merge de pandas. De este modo tendríamos un control más fino sobre la columna que sirve de índice para la fusión y el tipo de unión que se realiza, así como de los sufijos. Muestro a continuación la alternativa empleando la función merge:

In [32]:
ventas_regiones_merge = pd.merge(ventas_region_norte, ventas_region_sur, how='inner', on='id_producto', suffixes=('_norte', '_sur'))
ventas_regiones_merge.head()

             qtd_ventas_norte  qtd_ventas_sur
id_producto
100                       231             187
280                       417             754
353                        48              98